[project]
name = "uvtests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "typer>=0.12.5",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
]
